version: '3.8'

services:
  php-apache:
    build: .
    container_name: notes_php-apache
    ports:
      - 127.0.0.1:90:80
    volumes:
      - ./src:/var/www/html/

  mysql:
    image: mysql:latest
    container_name: notes_db
    ports:
      - 127.0.0.1:91:3306
    volumes:
      - ./database/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ROOT_PASSWORD: NotesPW
      MYSQL_DATABASE: NotesDB

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: notes_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 127.0.0.1:92:80
